name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  LANG: ja_JP.UTF-8

jobs:
  build:
    runs-on: ubuntu-latest
    name: build (JDK ${{ matrix.java }})
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
          - 11
          - 17

    steps:
      - name: Set locale
        run: |
          sudo locale-gen ${LANG}
          sudo update-locale LANG=${LANG}
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -V clean verify -Dmaven.javadoc.failOnError=false

